name: Publish Packages

on:
  push:
    branches: [ main ]
    paths:
      - 'Packages/**/package.json'
  
  workflow_dispatch:

jobs:
  publish:
    uses: Trickle-Charge/TrickleCharge-Infra/.github/workflows/publish-upm-packages.yml@main
    with:
      package-path: 'Packages/*'
      ignore-packages: 'com.tricklecharge.unity.template'
    secrets: inherit