name: Publish to Private Registry

on:
  push:
    paths:
      - 'Packages/**'
  
  workflow_dispatch:

jobs:
  trigger-shared-pipeline:
    uses: ./.github/workflows/publish-unity-packages.yml
    secrets: inherit